# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ClientService.proto',
  package='com.ataccama.one.onecfg.server.grpc',
  syntax='proto3',
  serialized_options=b'P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x43lientService.proto\x12#com.ataccama.one.onecfg.server.grpc\x1a\x1bgoogle/protobuf/empty.proto\"-\n\x10HeartbeatRequest\x12\x19\n\x11replicaIdentifier\x18\x01 \x01(\t2k\n\rClientService\x12Z\n\theartbeat\x12\x35.com.ataccama.one.onecfg.server.grpc.HeartbeatRequest\x1a\x16.google.protobuf.EmptyB\x02P\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_HEARTBEATREQUEST = _descriptor.Descriptor(
  name='HeartbeatRequest',
  full_name='com.ataccama.one.onecfg.server.grpc.HeartbeatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='replicaIdentifier', full_name='com.ataccama.one.onecfg.server.grpc.HeartbeatRequest.replicaIdentifier', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=134,
)

DESCRIPTOR.message_types_by_name['HeartbeatRequest'] = _HEARTBEATREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HeartbeatRequest = _reflection.GeneratedProtocolMessageType('HeartbeatRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATREQUEST,
  '__module__' : 'ClientService_pb2'
  # @@protoc_insertion_point(class_scope:com.ataccama.one.onecfg.server.grpc.HeartbeatRequest)
  })
_sym_db.RegisterMessage(HeartbeatRequest)


DESCRIPTOR._options = None

_CLIENTSERVICE = _descriptor.ServiceDescriptor(
  name='ClientService',
  full_name='com.ataccama.one.onecfg.server.grpc.ClientService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=136,
  serialized_end=243,
  methods=[
  _descriptor.MethodDescriptor(
    name='heartbeat',
    full_name='com.ataccama.one.onecfg.server.grpc.ClientService.heartbeat',
    index=0,
    containing_service=None,
    input_type=_HEARTBEATREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLIENTSERVICE)

DESCRIPTOR.services_by_name['ClientService'] = _CLIENTSERVICE

# @@protoc_insertion_point(module_scope)
