# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class PropertyRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    deploymentId: builtin___int = ...
    name: typing___Text = ...
    value: typing___Text = ...

    def __init__(self,
        *,
        deploymentId : typing___Optional[builtin___int] = None,
        name : typing___Optional[typing___Text] = None,
        value : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"deploymentId",b"deploymentId",u"name",b"name",u"value",b"value"]) -> None: ...
type___PropertyRequest = PropertyRequest

class GetPropertiesResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Property(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        TypeValue = typing___NewType('TypeValue', builtin___int)
        type___TypeValue = TypeValue
        Type: _Type
        class _Type(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[GetPropertiesResponse.Property.TypeValue]):
            DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
            RUNTIME = typing___cast(GetPropertiesResponse.Property.TypeValue, 0)
            PLATFORM = typing___cast(GetPropertiesResponse.Property.TypeValue, 1)
        RUNTIME = typing___cast(GetPropertiesResponse.Property.TypeValue, 0)
        PLATFORM = typing___cast(GetPropertiesResponse.Property.TypeValue, 1)
        type___Type = Type

        name: typing___Text = ...
        value: typing___Text = ...
        type: type___GetPropertiesResponse.Property.TypeValue = ...

        def __init__(self,
            *,
            name : typing___Optional[typing___Text] = None,
            value : typing___Optional[typing___Text] = None,
            type : typing___Optional[type___GetPropertiesResponse.Property.TypeValue] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"name",b"name",u"type",b"type",u"value",b"value"]) -> None: ...
    type___Property = Property

    version: typing___Text = ...

    @property
    def properties(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___GetPropertiesResponse.Property]: ...

    def __init__(self,
        *,
        properties : typing___Optional[typing___Iterable[type___GetPropertiesResponse.Property]] = None,
        version : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"properties",b"properties",u"version",b"version"]) -> None: ...
type___GetPropertiesResponse = GetPropertiesResponse

class GetLatestVersionResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    version: typing___Text = ...

    def __init__(self,
        *,
        version : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"version",b"version"]) -> None: ...
type___GetLatestVersionResponse = GetLatestVersionResponse

class PropertiesAppliedRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    replicaIdentifier: typing___Text = ...
    version: typing___Text = ...

    def __init__(self,
        *,
        replicaIdentifier : typing___Optional[typing___Text] = None,
        version : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"replicaIdentifier",b"replicaIdentifier",u"version",b"version"]) -> None: ...
type___PropertiesAppliedRequest = PropertiesAppliedRequest

class NothingToApplyRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    replicaIdentifier: typing___Text = ...

    def __init__(self,
        *,
        replicaIdentifier : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"replicaIdentifier",b"replicaIdentifier"]) -> None: ...
type___NothingToApplyRequest = NothingToApplyRequest
