"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

global___SearchType = SearchType
class _SearchType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[SearchType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    GLOBAL = SearchType.V(0)
    ENTITY_LISTING = SearchType.V(1)
class SearchType(metaclass=_SearchType):
    V = typing.NewType('V', builtins.int)
GLOBAL = SearchType.V(0)
ENTITY_LISTING = SearchType.V(1)

class TranslateQueryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SEARCH_REQUEST_FIELD_NUMBER: builtins.int

    @property
    def search_request(self) -> global___SearchRequest: ...

    def __init__(self,
        *,
        search_request : typing.Optional[global___SearchRequest] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"search_request",b"search_request"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"search_request",b"search_request"]) -> None: ...
global___TranslateQueryRequest = TranslateQueryRequest

class TranslateQueryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    AQL_QUERY_FIELD_NUMBER: builtins.int
    aql_query: typing.Text = ...

    def __init__(self,
        *,
        aql_query : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"aql_query",b"aql_query"]) -> None: ...
global___TranslateQueryResponse = TranslateQueryResponse

class SpellcheckAqlQueryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    AQL_QUERY_FIELD_NUMBER: builtins.int
    SEARCH_TYPE_FIELD_NUMBER: builtins.int
    LISTING_NODE_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    QUERY_ID_FIELD_NUMBER: builtins.int
    aql_query: typing.Text = ...
    search_type: global___SearchType.V = ...
    listing_node: typing.Text = ...
    user_id: typing.Text = ...
    query_id: typing.Text = ...

    def __init__(self,
        *,
        aql_query : typing.Text = ...,
        search_type : global___SearchType.V = ...,
        listing_node : typing.Text = ...,
        user_id : typing.Text = ...,
        query_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"aql_query",b"aql_query",u"listing_node",b"listing_node",u"query_id",b"query_id",u"search_type",b"search_type",u"user_id",b"user_id"]) -> None: ...
global___SpellcheckAqlQueryRequest = SpellcheckAqlQueryRequest

class SpellcheckAqlQueryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    AQL_QUERY_FIELD_NUMBER: builtins.int
    aql_query: typing.Text = ...

    def __init__(self,
        *,
        aql_query : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"aql_query",b"aql_query"]) -> None: ...
global___SpellcheckAqlQueryResponse = SpellcheckAqlQueryResponse

class AutocompleteQueryPartsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SEARCH_REQUEST_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    CARET_POSITION_FIELD_NUMBER: builtins.int
    NUM_SUGGESTIONS_FIELD_NUMBER: builtins.int
    NUM_HISTORY_FIELD_NUMBER: builtins.int
    value: typing.Text = ...
    caret_position: builtins.int = ...
    num_suggestions: builtins.int = ...
    num_history: builtins.int = ...

    @property
    def search_request(self) -> global___SearchRequest: ...

    def __init__(self,
        *,
        search_request : typing.Optional[global___SearchRequest] = ...,
        value : typing.Text = ...,
        caret_position : builtins.int = ...,
        num_suggestions : builtins.int = ...,
        num_history : builtins.int = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"search_request",b"search_request"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"caret_position",b"caret_position",u"num_history",b"num_history",u"num_suggestions",b"num_suggestions",u"search_request",b"search_request",u"value",b"value"]) -> None: ...
global___AutocompleteQueryPartsRequest = AutocompleteQueryPartsRequest

class AutocompleteQueryPartsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SUGGESTIONS_FIELD_NUMBER: builtins.int
    HISTORY_SUGGESTIONS_FIELD_NUMBER: builtins.int

    @property
    def suggestions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___QueryPart]: ...

    @property
    def history_suggestions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___HistoricalQueries]: ...

    def __init__(self,
        *,
        suggestions : typing.Optional[typing.Iterable[global___QueryPart]] = ...,
        history_suggestions : typing.Optional[typing.Iterable[global___HistoricalQueries]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"history_suggestions",b"history_suggestions",u"suggestions",b"suggestions"]) -> None: ...
global___AutocompleteQueryPartsResponse = AutocompleteQueryPartsResponse

class AutocompleteValuesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SEARCH_REQUEST_FIELD_NUMBER: builtins.int
    PART_INDEX_FIELD_NUMBER: builtins.int
    CARET_POSITION_FIELD_NUMBER: builtins.int
    NUM_SUGGESTIONS_FIELD_NUMBER: builtins.int
    part_index: builtins.int = ...
    caret_position: builtins.int = ...
    num_suggestions: builtins.int = ...

    @property
    def search_request(self) -> global___SearchRequest: ...

    def __init__(self,
        *,
        search_request : typing.Optional[global___SearchRequest] = ...,
        part_index : builtins.int = ...,
        caret_position : builtins.int = ...,
        num_suggestions : builtins.int = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"search_request",b"search_request"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"caret_position",b"caret_position",u"num_suggestions",b"num_suggestions",u"part_index",b"part_index",u"search_request",b"search_request"]) -> None: ...
global___AutocompleteValuesRequest = AutocompleteValuesRequest

class AutocompleteValuesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SUGGESTIONS_FIELD_NUMBER: builtins.int

    @property
    def suggestions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PartValue]: ...

    def __init__(self,
        *,
        suggestions : typing.Optional[typing.Iterable[global___PartValue]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"suggestions",b"suggestions"]) -> None: ...
global___AutocompleteValuesResponse = AutocompleteValuesResponse

class SearchRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    QUERY_PARTS_FIELD_NUMBER: builtins.int
    AQL_FILTERS_FIELD_NUMBER: builtins.int
    SEARCH_TYPE_FIELD_NUMBER: builtins.int
    LISTING_NODE_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    QUERY_ID_FIELD_NUMBER: builtins.int
    aql_filters: google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text] = ...
    search_type: global___SearchType.V = ...
    listing_node: typing.Text = ...
    user_id: typing.Text = ...
    query_id: typing.Text = ...

    @property
    def query_parts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___QueryPart]: ...

    def __init__(self,
        *,
        query_parts : typing.Optional[typing.Iterable[global___QueryPart]] = ...,
        aql_filters : typing.Optional[typing.Iterable[typing.Text]] = ...,
        search_type : global___SearchType.V = ...,
        listing_node : typing.Text = ...,
        user_id : typing.Text = ...,
        query_id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"aql_filters",b"aql_filters",u"listing_node",b"listing_node",u"query_id",b"query_id",u"query_parts",b"query_parts",u"search_type",b"search_type",u"user_id",b"user_id"]) -> None: ...
global___SearchRequest = SearchRequest

class QueryPart(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TYPE_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    type: typing.Text = ...

    @property
    def value(self) -> global___PartValue: ...

    def __init__(self,
        *,
        type : typing.Text = ...,
        value : typing.Optional[global___PartValue] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"value",b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"type",b"type",u"value",b"value"]) -> None: ...
global___QueryPart = QueryPart

class PartValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    VALUE_FIELD_NUMBER: builtins.int
    value: typing.Text = ...

    def __init__(self,
        *,
        value : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"value",b"value"]) -> None: ...
global___PartValue = PartValue

class HistoricalQueries(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    QUERY_PARTS_FIELD_NUMBER: builtins.int

    @property
    def query_parts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___QueryPart]: ...

    def __init__(self,
        *,
        query_parts : typing.Optional[typing.Iterable[global___QueryPart]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"query_parts",b"query_parts"]) -> None: ...
global___HistoricalQueries = HistoricalQueries
