"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

global___ModelType = ModelType
class _ModelType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ModelType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    TIME_INDEPENDENT = ModelType.V(0)
    TIME_DEPENDENT = ModelType.V(1)
    ANOMALY_DETECTION_NOT_PERFORMED = ModelType.V(2)
class ModelType(metaclass=_ModelType):
    V = typing.NewType('V', builtins.int)
TIME_INDEPENDENT = ModelType.V(0)
TIME_DEPENDENT = ModelType.V(1)
ANOMALY_DETECTION_NOT_PERFORMED = ModelType.V(2)

global___FeedbackType = FeedbackType
class _FeedbackType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[FeedbackType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    NO_FEEDBACK = FeedbackType.V(0)
    ANOMALOUS = FeedbackType.V(1)
    NOT_ANOMALOUS = FeedbackType.V(2)
class FeedbackType(metaclass=_FeedbackType):
    V = typing.NewType('V', builtins.int)
NO_FEEDBACK = FeedbackType.V(0)
ANOMALOUS = FeedbackType.V(1)
NOT_ANOMALOUS = FeedbackType.V(2)

global___CategoryType = CategoryType
class _CategoryType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CategoryType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    GENERIC = CategoryType.V(0)
    FINGERPRINTS = CategoryType.V(1)
    FREQUENCIES = CategoryType.V(2)
class CategoryType(metaclass=_CategoryType):
    V = typing.NewType('V', builtins.int)
GENERIC = CategoryType.V(0)
FINGERPRINTS = CategoryType.V(1)
FREQUENCIES = CategoryType.V(2)

class DetectAnomaliesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    ENTITY_TYPE_FIELD_NUMBER: builtins.int
    HCN_FIELD_NUMBER: builtins.int
    PERIODICITY_FIELD_NUMBER: builtins.int
    id: typing.Text = ...
    entity_type: typing.Text = ...
    hcn: builtins.int = ...
    periodicity: builtins.int = ...

    def __init__(self,
        *,
        id : typing.Text = ...,
        entity_type : typing.Text = ...,
        hcn : builtins.int = ...,
        periodicity : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"entity_type",b"entity_type",u"hcn",b"hcn",u"id",b"id",u"periodicity",b"periodicity"]) -> None: ...
global___DetectAnomaliesRequest = DetectAnomaliesRequest

class DetectAnomaliesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    ENTITY_TYPE_FIELD_NUMBER: builtins.int
    MODEL_FIELD_NUMBER: builtins.int
    DETECTED_DATA_POINTS_FIELD_NUMBER: builtins.int
    id: typing.Text = ...
    entity_type: typing.Text = ...
    model: global___ModelType.V = ...

    @property
    def detected_data_points(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DetectedDataPoint]: ...

    def __init__(self,
        *,
        id : typing.Text = ...,
        entity_type : typing.Text = ...,
        model : global___ModelType.V = ...,
        detected_data_points : typing.Optional[typing.Iterable[global___DetectedDataPoint]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"detected_data_points",b"detected_data_points",u"entity_type",b"entity_type",u"id",b"id",u"model",b"model"]) -> None: ...
global___DetectAnomaliesResponse = DetectAnomaliesResponse

class DetectedDataPoint(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    HCN_FIELD_NUMBER: builtins.int
    ANOMALOUS_FIELD_NUMBER: builtins.int
    CATEGORIES_RESULTS_FIELD_NUMBER: builtins.int
    hcn: builtins.int = ...
    anomalous: builtins.bool = ...

    @property
    def categories_results(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CategoryResult]: ...

    def __init__(self,
        *,
        hcn : builtins.int = ...,
        anomalous : builtins.bool = ...,
        categories_results : typing.Optional[typing.Iterable[global___CategoryResult]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"anomalous",b"anomalous",u"categories_results",b"categories_results",u"hcn",b"hcn"]) -> None: ...
global___DetectedDataPoint = DetectedDataPoint

class CategoryResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class FeaturesResultsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...

        @property
        def value(self) -> global___FeatureResult: ...

        def __init__(self,
            *,
            key : typing.Text = ...,
            value : typing.Optional[global___FeatureResult] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    CATEGORY_NAME_FIELD_NUMBER: builtins.int
    ANOMALY_SCORE_FIELD_NUMBER: builtins.int
    ANOMALOUS_FIELD_NUMBER: builtins.int
    FEATURES_RESULTS_FIELD_NUMBER: builtins.int
    category_name: typing.Text = ...
    anomaly_score: builtins.float = ...
    anomalous: builtins.bool = ...

    @property
    def features_results(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, global___FeatureResult]: ...

    def __init__(self,
        *,
        category_name : typing.Text = ...,
        anomaly_score : builtins.float = ...,
        anomalous : builtins.bool = ...,
        features_results : typing.Optional[typing.Mapping[typing.Text, global___FeatureResult]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"anomalous",b"anomalous",u"anomaly_score",b"anomaly_score",u"category_name",b"category_name",u"features_results",b"features_results"]) -> None: ...
global___CategoryResult = CategoryResult

class FeatureResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ANOMALY_SCORE_FIELD_NUMBER: builtins.int
    ANOMALOUS_FIELD_NUMBER: builtins.int
    EXPECTED_VALUE_LOWER_BOUND_FIELD_NUMBER: builtins.int
    EXPECTED_VALUE_FIELD_NUMBER: builtins.int
    EXPECTED_VALUE_UPPER_BOUND_FIELD_NUMBER: builtins.int
    anomaly_score: builtins.float = ...
    anomalous: builtins.bool = ...
    expected_value_lower_bound: builtins.float = ...
    expected_value: builtins.float = ...
    expected_value_upper_bound: builtins.float = ...

    def __init__(self,
        *,
        anomaly_score : builtins.float = ...,
        anomalous : builtins.bool = ...,
        expected_value_lower_bound : builtins.float = ...,
        expected_value : builtins.float = ...,
        expected_value_upper_bound : builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"anomalous",b"anomalous",u"anomaly_score",b"anomaly_score",u"expected_value",b"expected_value",u"expected_value_lower_bound",b"expected_value_lower_bound",u"expected_value_upper_bound",b"expected_value_upper_bound"]) -> None: ...
global___FeatureResult = FeatureResult

class GetHistoryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    ENTITY_TYPE_FIELD_NUMBER: builtins.int
    HCN_FIELD_NUMBER: builtins.int
    HISTORY_LENGTH_FIELD_NUMBER: builtins.int
    id: typing.Text = ...
    entity_type: typing.Text = ...
    hcn: builtins.int = ...
    history_length: builtins.int = ...

    def __init__(self,
        *,
        id : typing.Text = ...,
        entity_type : typing.Text = ...,
        hcn : builtins.int = ...,
        history_length : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"entity_type",b"entity_type",u"hcn",b"hcn",u"history_length",b"history_length",u"id",b"id"]) -> None: ...
global___GetHistoryRequest = GetHistoryRequest

class GetHistoryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    HCN_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    FEEDBACK_FIELD_NUMBER: builtins.int
    CATEGORY_DATA_FIELD_NUMBER: builtins.int
    id: typing.Text = ...
    hcn: builtins.int = ...
    feedback: global___FeedbackType.V = ...

    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    @property
    def category_data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Category]: ...

    def __init__(self,
        *,
        id : typing.Text = ...,
        hcn : builtins.int = ...,
        created_at : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        feedback : global___FeedbackType.V = ...,
        category_data : typing.Optional[typing.Iterable[global___Category]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"created_at",b"created_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"category_data",b"category_data",u"created_at",b"created_at",u"feedback",b"feedback",u"hcn",b"hcn",u"id",b"id"]) -> None: ...
global___GetHistoryResponse = GetHistoryResponse

class Category(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CATEGORY_TYPE_FIELD_NUMBER: builtins.int
    CATEGORY_NAME_FIELD_NUMBER: builtins.int
    STATISTICS_VALUES_FIELD_NUMBER: builtins.int
    category_type: global___CategoryType.V = ...
    category_name: typing.Text = ...

    @property
    def statistics_values(self) -> global___Statistics: ...

    def __init__(self,
        *,
        category_type : global___CategoryType.V = ...,
        category_name : typing.Text = ...,
        statistics_values : typing.Optional[global___Statistics] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"statistics_values",b"statistics_values"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"category_name",b"category_name",u"category_type",b"category_type",u"statistics_values",b"statistics_values"]) -> None: ...
global___Category = Category

class Statistics(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DICT_INT32_FIELD_NUMBER: builtins.int
    DICT_INT64_FIELD_NUMBER: builtins.int
    DICT_DOUBLE_FIELD_NUMBER: builtins.int
    ARRAY_DOUBLE_FIELD_NUMBER: builtins.int
    ARRAY_STRING_FIELD_NUMBER: builtins.int
    FREQUENCIES_FIELD_NUMBER: builtins.int

    @property
    def dict_int32(self) -> global___DictStringInt32: ...

    @property
    def dict_int64(self) -> global___DictStringInt64: ...

    @property
    def dict_double(self) -> global___DictStringDouble: ...

    @property
    def array_double(self) -> global___DoubleArray: ...

    @property
    def array_string(self) -> global___StringArray: ...

    @property
    def frequencies(self) -> global___Frequencies: ...

    def __init__(self,
        *,
        dict_int32 : typing.Optional[global___DictStringInt32] = ...,
        dict_int64 : typing.Optional[global___DictStringInt64] = ...,
        dict_double : typing.Optional[global___DictStringDouble] = ...,
        array_double : typing.Optional[global___DoubleArray] = ...,
        array_string : typing.Optional[global___StringArray] = ...,
        frequencies : typing.Optional[global___Frequencies] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"array_double",b"array_double",u"array_string",b"array_string",u"dict_double",b"dict_double",u"dict_int32",b"dict_int32",u"dict_int64",b"dict_int64",u"frequencies",b"frequencies",u"oneof_data",b"oneof_data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"array_double",b"array_double",u"array_string",b"array_string",u"dict_double",b"dict_double",u"dict_int32",b"dict_int32",u"dict_int64",b"dict_int64",u"frequencies",b"frequencies",u"oneof_data",b"oneof_data"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal[u"oneof_data",b"oneof_data"]) -> typing_extensions.Literal["dict_int32","dict_int64","dict_double","array_double","array_string","frequencies"]: ...
global___Statistics = Statistics

class DoubleArray(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ARRAY_FIELD_NUMBER: builtins.int
    array: google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float] = ...

    def __init__(self,
        *,
        array : typing.Optional[typing.Iterable[builtins.float]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"array",b"array"]) -> None: ...
global___DoubleArray = DoubleArray

class StringArray(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ARRAY_FIELD_NUMBER: builtins.int
    array: google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text] = ...

    def __init__(self,
        *,
        array : typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"array",b"array"]) -> None: ...
global___StringArray = StringArray

class DictStringInt32(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class DictEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: builtins.int = ...

        def __init__(self,
            *,
            key : typing.Text = ...,
            value : builtins.int = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    DICT_FIELD_NUMBER: builtins.int

    @property
    def dict(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, builtins.int]: ...

    def __init__(self,
        *,
        dict : typing.Optional[typing.Mapping[typing.Text, builtins.int]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"dict",b"dict"]) -> None: ...
global___DictStringInt32 = DictStringInt32

class DictStringInt64(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class DictEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: builtins.int = ...

        def __init__(self,
            *,
            key : typing.Text = ...,
            value : builtins.int = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    DICT_FIELD_NUMBER: builtins.int

    @property
    def dict(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, builtins.int]: ...

    def __init__(self,
        *,
        dict : typing.Optional[typing.Mapping[typing.Text, builtins.int]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"dict",b"dict"]) -> None: ...
global___DictStringInt64 = DictStringInt64

class DictStringDouble(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class DictEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: builtins.float = ...

        def __init__(self,
            *,
            key : typing.Text = ...,
            value : builtins.float = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    DICT_FIELD_NUMBER: builtins.int

    @property
    def dict(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, builtins.float]: ...

    def __init__(self,
        *,
        dict : typing.Optional[typing.Mapping[typing.Text, builtins.float]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"dict",b"dict"]) -> None: ...
global___DictStringDouble = DictStringDouble

class Frequencies(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class HeadEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: builtins.int = ...

        def __init__(self,
            *,
            key : typing.Text = ...,
            value : builtins.int = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    class TailEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: builtins.int = ...

        def __init__(self,
            *,
            key : typing.Text = ...,
            value : builtins.int = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    HEAD_FIELD_NUMBER: builtins.int
    TAIL_FIELD_NUMBER: builtins.int
    ROW_COUNT_FIELD_NUMBER: builtins.int
    DISTINCT_COUNT_FIELD_NUMBER: builtins.int
    row_count: builtins.int = ...
    distinct_count: builtins.int = ...

    @property
    def head(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, builtins.int]: ...

    @property
    def tail(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, builtins.int]: ...

    def __init__(self,
        *,
        head : typing.Optional[typing.Mapping[typing.Text, builtins.int]] = ...,
        tail : typing.Optional[typing.Mapping[typing.Text, builtins.int]] = ...,
        row_count : builtins.int = ...,
        distinct_count : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"distinct_count",b"distinct_count",u"head",b"head",u"row_count",b"row_count",u"tail",b"tail"]) -> None: ...
global___Frequencies = Frequencies
