"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

global___MatchingPhase = MatchingPhase
class _MatchingPhase(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[MatchingPhase.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    NOT_CREATED = MatchingPhase.V(0)
    INITIALIZING_MATCHING = MatchingPhase.V(1)
    TRAINING_MODEL = MatchingPhase.V(2)
    FETCHING_RECORDS = MatchingPhase.V(3)
    BLOCKING_RECORDS = MatchingPhase.V(4)
    SCORING_PAIRS = MatchingPhase.V(5)
    CLUSTERING_RECORDS = MatchingPhase.V(6)
    GENERATING_PROPOSALS = MatchingPhase.V(7)
    EXTRACTING_RULES = MatchingPhase.V(8)
    READY = MatchingPhase.V(9)
    ERROR = MatchingPhase.V(10)
class MatchingPhase(metaclass=_MatchingPhase):
    V = typing.NewType('V', builtins.int)
NOT_CREATED = MatchingPhase.V(0)
INITIALIZING_MATCHING = MatchingPhase.V(1)
TRAINING_MODEL = MatchingPhase.V(2)
FETCHING_RECORDS = MatchingPhase.V(3)
BLOCKING_RECORDS = MatchingPhase.V(4)
SCORING_PAIRS = MatchingPhase.V(5)
CLUSTERING_RECORDS = MatchingPhase.V(6)
GENERATING_PROPOSALS = MatchingPhase.V(7)
EXTRACTING_RULES = MatchingPhase.V(8)
READY = MatchingPhase.V(9)
ERROR = MatchingPhase.V(10)

global___ComputationState = ComputationState
class _ComputationState(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ComputationState.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    NOT_PLANNED = ComputationState.V(0)
    PLANNED = ComputationState.V(1)
    FINISHED = ComputationState.V(2)
class ComputationState(metaclass=_ComputationState):
    V = typing.NewType('V', builtins.int)
NOT_PLANNED = ComputationState.V(0)
PLANNED = ComputationState.V(1)
FINISHED = ComputationState.V(2)

global___ColumnType = ColumnType
class _ColumnType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ColumnType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    STRING = ColumnType.V(0)
    INTEGER = ColumnType.V(1)
    DAY = ColumnType.V(2)
    BOOLEAN = ColumnType.V(3)
    LONG = ColumnType.V(4)
    DATETIME = ColumnType.V(5)
    FLOAT = ColumnType.V(6)
class ColumnType(metaclass=_ColumnType):
    V = typing.NewType('V', builtins.int)
STRING = ColumnType.V(0)
INTEGER = ColumnType.V(1)
DAY = ColumnType.V(2)
BOOLEAN = ColumnType.V(3)
LONG = ColumnType.V(4)
DATETIME = ColumnType.V(5)
FLOAT = ColumnType.V(6)

global___RestartType = RestartType
class _RestartType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[RestartType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    RESET_TO_EVALUATION = RestartType.V(0)
    RESET_TO_TRAINING = RestartType.V(1)
    CLEAR_TRAINING_PAIRS = RestartType.V(2)
    RESET_ALL = RestartType.V(3)
class RestartType(metaclass=_RestartType):
    V = typing.NewType('V', builtins.int)
RESET_TO_EVALUATION = RestartType.V(0)
RESET_TO_TRAINING = RestartType.V(1)
CLEAR_TRAINING_PAIRS = RestartType.V(2)
RESET_ALL = RestartType.V(3)

global___MatchingDecision = MatchingDecision
class _MatchingDecision(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[MatchingDecision.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    UNKNOWN = MatchingDecision.V(0)
    MATCH = MatchingDecision.V(1)
    DISTINCT = MatchingDecision.V(2)
class MatchingDecision(metaclass=_MatchingDecision):
    V = typing.NewType('V', builtins.int)
UNKNOWN = MatchingDecision.V(0)
MATCH = MatchingDecision.V(1)
DISTINCT = MatchingDecision.V(2)

global___ProposalType = ProposalType
class _ProposalType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProposalType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    ALL = ProposalType.V(0)
    MERGE = ProposalType.V(1)
    SPLIT = ProposalType.V(2)
class ProposalType(metaclass=_ProposalType):
    V = typing.NewType('V', builtins.int)
ALL = ProposalType.V(0)
MERGE = ProposalType.V(1)
SPLIT = ProposalType.V(2)

class ErrorMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MESSAGE_FIELD_NUMBER: builtins.int
    PHASE_FIELD_NUMBER: builtins.int
    message: typing.Text = ...
    phase: global___MatchingPhase.V = ...

    def __init__(self,
        *,
        message : typing.Text = ...,
        phase : global___MatchingPhase.V = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"message",b"message",u"phase",b"phase"]) -> None: ...
global___ErrorMessage = ErrorMessage

class StatusMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MATCHING_ID_FIELD_NUMBER: builtins.int
    PHASE_FIELD_NUMBER: builtins.int
    PROGRESS_FIELD_NUMBER: builtins.int
    MODEL_UPDATE_TIME_FIELD_NUMBER: builtins.int
    MATCH_TRAINING_PAIRS_COUNT_FIELD_NUMBER: builtins.int
    DISTINCT_TRAINING_PAIRS_COUNT_FIELD_NUMBER: builtins.int
    USED_COLUMNS_COUNT_FIELD_NUMBER: builtins.int
    CLUSTERING_STATE_FIELD_NUMBER: builtins.int
    RECORDS_MATCHING_STATUS_FIELD_NUMBER: builtins.int
    RULES_EXTRACTION_STATUS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    MODEL_QUALITY_FIELD_NUMBER: builtins.int
    phase: global___MatchingPhase.V = ...
    progress: builtins.float = ...
    match_training_pairs_count: builtins.int = ...
    distinct_training_pairs_count: builtins.int = ...
    used_columns_count: builtins.int = ...
    clustering_state: global___ComputationState.V = ...
    model_quality: builtins.float = ...

    @property
    def matching_id(self) -> global___MatchingId: ...

    @property
    def model_update_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    @property
    def records_matching_status(self) -> global___RecordsMatchingStatus: ...

    @property
    def rules_extraction_status(self) -> global___RulesExtractionStatus: ...

    @property
    def error(self) -> global___ErrorMessage: ...

    def __init__(self,
        *,
        matching_id : typing.Optional[global___MatchingId] = ...,
        phase : global___MatchingPhase.V = ...,
        progress : builtins.float = ...,
        model_update_time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        match_training_pairs_count : builtins.int = ...,
        distinct_training_pairs_count : builtins.int = ...,
        used_columns_count : builtins.int = ...,
        clustering_state : global___ComputationState.V = ...,
        records_matching_status : typing.Optional[global___RecordsMatchingStatus] = ...,
        rules_extraction_status : typing.Optional[global___RulesExtractionStatus] = ...,
        error : typing.Optional[global___ErrorMessage] = ...,
        model_quality : builtins.float = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"error",b"error",u"matching_id",b"matching_id",u"model_update_time",b"model_update_time",u"records_matching_status",b"records_matching_status",u"rules_extraction_status",b"rules_extraction_status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"clustering_state",b"clustering_state",u"distinct_training_pairs_count",b"distinct_training_pairs_count",u"error",b"error",u"match_training_pairs_count",b"match_training_pairs_count",u"matching_id",b"matching_id",u"model_quality",b"model_quality",u"model_update_time",b"model_update_time",u"phase",b"phase",u"progress",b"progress",u"records_matching_status",b"records_matching_status",u"rules_extraction_status",b"rules_extraction_status",u"used_columns_count",b"used_columns_count"]) -> None: ...
global___StatusMessage = StatusMessage

class RecordsMatchingStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STATE_FIELD_NUMBER: builtins.int
    MERGE_PROPOSALS_COUNT_FIELD_NUMBER: builtins.int
    SPLIT_PROPOSALS_COUNT_FIELD_NUMBER: builtins.int
    CACHED_PROPOSALS_COUNT_FIELD_NUMBER: builtins.int
    CONFIDENCE_THRESHOLD_FIELD_NUMBER: builtins.int
    state: global___ComputationState.V = ...
    merge_proposals_count: builtins.int = ...
    split_proposals_count: builtins.int = ...
    cached_proposals_count: builtins.int = ...
    confidence_threshold: builtins.float = ...

    def __init__(self,
        *,
        state : global___ComputationState.V = ...,
        merge_proposals_count : builtins.int = ...,
        split_proposals_count : builtins.int = ...,
        cached_proposals_count : builtins.int = ...,
        confidence_threshold : builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"cached_proposals_count",b"cached_proposals_count",u"confidence_threshold",b"confidence_threshold",u"merge_proposals_count",b"merge_proposals_count",u"split_proposals_count",b"split_proposals_count",u"state",b"state"]) -> None: ...
global___RecordsMatchingStatus = RecordsMatchingStatus

class RulesExtractionStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STATE_FIELD_NUMBER: builtins.int
    RULES_EXTRACTED_COUNT_FIELD_NUMBER: builtins.int
    MIN_MATCH_CONFIDENCE_FIELD_NUMBER: builtins.int
    MIN_DISTINCT_CONFIDENCE_FIELD_NUMBER: builtins.int
    state: global___ComputationState.V = ...
    rules_extracted_count: builtins.int = ...
    min_match_confidence: builtins.float = ...
    min_distinct_confidence: builtins.float = ...

    def __init__(self,
        *,
        state : global___ComputationState.V = ...,
        rules_extracted_count : builtins.int = ...,
        min_match_confidence : builtins.float = ...,
        min_distinct_confidence : builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"min_distinct_confidence",b"min_distinct_confidence",u"min_match_confidence",b"min_match_confidence",u"rules_extracted_count",b"rules_extracted_count",u"state",b"state"]) -> None: ...
global___RulesExtractionStatus = RulesExtractionStatus

class MatchingId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ENTITY_NAME_FIELD_NUMBER: builtins.int
    LAYER_NAME_FIELD_NUMBER: builtins.int
    entity_name: typing.Text = ...
    layer_name: typing.Text = ...

    def __init__(self,
        *,
        entity_name : typing.Text = ...,
        layer_name : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"entity_name",b"entity_name",u"layer_name",b"layer_name"]) -> None: ...
global___MatchingId = MatchingId

class MdcColumn(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TYPE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    ISENGINE_FIELD_NUMBER: builtins.int
    type: global___ColumnType.V = ...
    name: typing.Text = ...
    isEngine: builtins.bool = ...

    def __init__(self,
        *,
        type : global___ColumnType.V = ...,
        name : typing.Text = ...,
        isEngine : builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"isEngine",b"isEngine",u"name",b"name",u"type",b"type"]) -> None: ...
global___MdcColumn = MdcColumn

class InitMatchingRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MATCHING_ID_FIELD_NUMBER: builtins.int
    COLUMNS_FIELD_NUMBER: builtins.int
    MATCHING_ID_COLUMN_FIELD_NUMBER: builtins.int
    RECORD_ID_COLUMN_FIELD_NUMBER: builtins.int

    @property
    def matching_id(self) -> global___MatchingId: ...

    @property
    def columns(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MdcColumn]: ...

    @property
    def matching_id_column(self) -> global___MdcColumn: ...

    @property
    def record_id_column(self) -> global___MdcColumn: ...

    def __init__(self,
        *,
        matching_id : typing.Optional[global___MatchingId] = ...,
        columns : typing.Optional[typing.Iterable[global___MdcColumn]] = ...,
        matching_id_column : typing.Optional[global___MdcColumn] = ...,
        record_id_column : typing.Optional[global___MdcColumn] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id",u"matching_id_column",b"matching_id_column",u"record_id_column",b"record_id_column"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"columns",b"columns",u"matching_id",b"matching_id",u"matching_id_column",b"matching_id_column",u"record_id_column",b"record_id_column"]) -> None: ...
global___InitMatchingRequest = InitMatchingRequest

class InitMatchingResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STATUS_FIELD_NUMBER: builtins.int

    @property
    def status(self) -> global___StatusMessage: ...

    def __init__(self,
        *,
        status : typing.Optional[global___StatusMessage] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"status",b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"status",b"status"]) -> None: ...
global___InitMatchingResponse = InitMatchingResponse

class InitMatchingFromFileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MATCHING_ID_FIELD_NUMBER: builtins.int
    COLUMNS_FIELD_NUMBER: builtins.int
    MATCHING_ID_COLUMN_FIELD_NUMBER: builtins.int
    RECORD_ID_COLUMN_FIELD_NUMBER: builtins.int
    FILE_PATH_FIELD_NUMBER: builtins.int
    DIALECT_FIELD_NUMBER: builtins.int
    file_path: typing.Text = ...
    dialect: typing.Text = ...

    @property
    def matching_id(self) -> global___MatchingId: ...

    @property
    def columns(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MdcColumn]: ...

    @property
    def matching_id_column(self) -> global___MdcColumn: ...

    @property
    def record_id_column(self) -> global___MdcColumn: ...

    def __init__(self,
        *,
        matching_id : typing.Optional[global___MatchingId] = ...,
        columns : typing.Optional[typing.Iterable[global___MdcColumn]] = ...,
        matching_id_column : typing.Optional[global___MdcColumn] = ...,
        record_id_column : typing.Optional[global___MdcColumn] = ...,
        file_path : typing.Text = ...,
        dialect : typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id",u"matching_id_column",b"matching_id_column",u"record_id_column",b"record_id_column"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"columns",b"columns",u"dialect",b"dialect",u"file_path",b"file_path",u"matching_id",b"matching_id",u"matching_id_column",b"matching_id_column",u"record_id_column",b"record_id_column"]) -> None: ...
global___InitMatchingFromFileRequest = InitMatchingFromFileRequest

class InitMatchingFromFileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STATUS_FIELD_NUMBER: builtins.int

    @property
    def status(self) -> global___StatusMessage: ...

    def __init__(self,
        *,
        status : typing.Optional[global___StatusMessage] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"status",b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"status",b"status"]) -> None: ...
global___InitMatchingFromFileResponse = InitMatchingFromFileResponse

class RestartMatchingRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MATCHING_ID_FIELD_NUMBER: builtins.int
    RESTART_TYPE_FIELD_NUMBER: builtins.int
    restart_type: global___RestartType.V = ...

    @property
    def matching_id(self) -> global___MatchingId: ...

    def __init__(self,
        *,
        matching_id : typing.Optional[global___MatchingId] = ...,
        restart_type : global___RestartType.V = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id",u"restart_type",b"restart_type"]) -> None: ...
global___RestartMatchingRequest = RestartMatchingRequest

class RestartMatchingResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STATUS_FIELD_NUMBER: builtins.int

    @property
    def status(self) -> global___StatusMessage: ...

    def __init__(self,
        *,
        status : typing.Optional[global___StatusMessage] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"status",b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"status",b"status"]) -> None: ...
global___RestartMatchingResponse = RestartMatchingResponse

class PairIds(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID1_FIELD_NUMBER: builtins.int
    ID2_FIELD_NUMBER: builtins.int
    id1: builtins.int = ...
    id2: builtins.int = ...

    def __init__(self,
        *,
        id1 : builtins.int = ...,
        id2 : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"id1",b"id1",u"id2",b"id2"]) -> None: ...
global___PairIds = PairIds

class GetTrainingPairRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MATCHING_ID_FIELD_NUMBER: builtins.int

    @property
    def matching_id(self) -> global___MatchingId: ...

    def __init__(self,
        *,
        matching_id : typing.Optional[global___MatchingId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id"]) -> None: ...
global___GetTrainingPairRequest = GetTrainingPairRequest

class GetTrainingPairResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PAIR_FIELD_NUMBER: builtins.int

    @property
    def pair(self) -> global___PairIds: ...

    def __init__(self,
        *,
        pair : typing.Optional[global___PairIds] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"pair",b"pair"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"pair",b"pair"]) -> None: ...
global___GetTrainingPairResponse = GetTrainingPairResponse

class TrainingPair(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PAIR_FIELD_NUMBER: builtins.int
    DECISION_FIELD_NUMBER: builtins.int
    decision: global___MatchingDecision.V = ...

    @property
    def pair(self) -> global___PairIds: ...

    def __init__(self,
        *,
        pair : typing.Optional[global___PairIds] = ...,
        decision : global___MatchingDecision.V = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"pair",b"pair"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"decision",b"decision",u"pair",b"pair"]) -> None: ...
global___TrainingPair = TrainingPair

class GetExistingTrainingPairsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MATCHING_ID_FIELD_NUMBER: builtins.int

    @property
    def matching_id(self) -> global___MatchingId: ...

    def __init__(self,
        *,
        matching_id : typing.Optional[global___MatchingId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id"]) -> None: ...
global___GetExistingTrainingPairsRequest = GetExistingTrainingPairsRequest

class GetExistingTrainingPairsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PAIRS_FIELD_NUMBER: builtins.int

    @property
    def pairs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TrainingPair]: ...

    def __init__(self,
        *,
        pairs : typing.Optional[typing.Iterable[global___TrainingPair]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"pairs",b"pairs"]) -> None: ...
global___GetExistingTrainingPairsResponse = GetExistingTrainingPairsResponse

class UpdateTrainingPairRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MATCHING_ID_FIELD_NUMBER: builtins.int
    TRAINING_PAIR_FIELD_NUMBER: builtins.int

    @property
    def matching_id(self) -> global___MatchingId: ...

    @property
    def training_pair(self) -> global___TrainingPair: ...

    def __init__(self,
        *,
        matching_id : typing.Optional[global___MatchingId] = ...,
        training_pair : typing.Optional[global___TrainingPair] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id",u"training_pair",b"training_pair"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id",u"training_pair",b"training_pair"]) -> None: ...
global___UpdateTrainingPairRequest = UpdateTrainingPairRequest

class UpdateTrainingPairResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STATUS_FIELD_NUMBER: builtins.int

    @property
    def status(self) -> global___StatusMessage: ...

    def __init__(self,
        *,
        status : typing.Optional[global___StatusMessage] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"status",b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"status",b"status"]) -> None: ...
global___UpdateTrainingPairResponse = UpdateTrainingPairResponse

class EvaluateRecordsMatchingRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MATCHING_ID_FIELD_NUMBER: builtins.int
    CACHED_PROPOSALS_COUNT_FIELD_NUMBER: builtins.int
    CONFIDENCE_THRESHOLD_FIELD_NUMBER: builtins.int
    cached_proposals_count: builtins.int = ...
    confidence_threshold: builtins.float = ...

    @property
    def matching_id(self) -> global___MatchingId: ...

    def __init__(self,
        *,
        matching_id : typing.Optional[global___MatchingId] = ...,
        cached_proposals_count : builtins.int = ...,
        confidence_threshold : builtins.float = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"cached_proposals_count",b"cached_proposals_count",u"confidence_threshold",b"confidence_threshold",u"matching_id",b"matching_id"]) -> None: ...
global___EvaluateRecordsMatchingRequest = EvaluateRecordsMatchingRequest

class EvaluateRecordsMatchingResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STATUS_FIELD_NUMBER: builtins.int

    @property
    def status(self) -> global___StatusMessage: ...

    def __init__(self,
        *,
        status : typing.Optional[global___StatusMessage] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"status",b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"status",b"status"]) -> None: ...
global___EvaluateRecordsMatchingResponse = EvaluateRecordsMatchingResponse

class ColumnScore(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    COLUMN_NAME_FIELD_NUMBER: builtins.int
    SCORE_FIELD_NUMBER: builtins.int
    column_name: typing.Text = ...
    score: builtins.float = ...

    def __init__(self,
        *,
        column_name : typing.Text = ...,
        score : builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"column_name",b"column_name",u"score",b"score"]) -> None: ...
global___ColumnScore = ColumnScore

class MatchingProposal(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PAIR_FIELD_NUMBER: builtins.int
    DECISION_FIELD_NUMBER: builtins.int
    CONFIDENCE_FIELD_NUMBER: builtins.int
    KEY_COLUMNS_FIELD_NUMBER: builtins.int
    COLUMN_SCORES_FIELD_NUMBER: builtins.int
    decision: global___ProposalType.V = ...
    confidence: builtins.float = ...
    key_columns: google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text] = ...

    @property
    def pair(self) -> global___PairIds: ...

    @property
    def column_scores(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ColumnScore]: ...

    def __init__(self,
        *,
        pair : typing.Optional[global___PairIds] = ...,
        decision : global___ProposalType.V = ...,
        confidence : builtins.float = ...,
        key_columns : typing.Optional[typing.Iterable[typing.Text]] = ...,
        column_scores : typing.Optional[typing.Iterable[global___ColumnScore]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"pair",b"pair"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"column_scores",b"column_scores",u"confidence",b"confidence",u"decision",b"decision",u"key_columns",b"key_columns",u"pair",b"pair"]) -> None: ...
global___MatchingProposal = MatchingProposal

class GetProposalRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MATCHING_ID_FIELD_NUMBER: builtins.int
    PAIR_FIELD_NUMBER: builtins.int

    @property
    def matching_id(self) -> global___MatchingId: ...

    @property
    def pair(self) -> global___PairIds: ...

    def __init__(self,
        *,
        matching_id : typing.Optional[global___MatchingId] = ...,
        pair : typing.Optional[global___PairIds] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id",u"pair",b"pair"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id",u"pair",b"pair"]) -> None: ...
global___GetProposalRequest = GetProposalRequest

class GetProposalResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PROPOSAL_FIELD_NUMBER: builtins.int

    @property
    def proposal(self) -> global___MatchingProposal: ...

    def __init__(self,
        *,
        proposal : typing.Optional[global___MatchingProposal] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"proposal",b"proposal"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"proposal",b"proposal"]) -> None: ...
global___GetProposalResponse = GetProposalResponse

class GetProposalsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MATCHING_ID_FIELD_NUMBER: builtins.int
    PROPOSALS_COUNT_FIELD_NUMBER: builtins.int
    CONFIDENCE_THRESHOLD_FIELD_NUMBER: builtins.int
    DECISION_FIELD_NUMBER: builtins.int
    proposals_count: builtins.int = ...
    confidence_threshold: builtins.float = ...
    decision: global___ProposalType.V = ...

    @property
    def matching_id(self) -> global___MatchingId: ...

    def __init__(self,
        *,
        matching_id : typing.Optional[global___MatchingId] = ...,
        proposals_count : builtins.int = ...,
        confidence_threshold : builtins.float = ...,
        decision : global___ProposalType.V = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"confidence_threshold",b"confidence_threshold",u"decision",b"decision",u"matching_id",b"matching_id",u"proposals_count",b"proposals_count"]) -> None: ...
global___GetProposalsRequest = GetProposalsRequest

class GetProposalsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PROPOSALS_FIELD_NUMBER: builtins.int

    @property
    def proposals(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MatchingProposal]: ...

    def __init__(self,
        *,
        proposals : typing.Optional[typing.Iterable[global___MatchingProposal]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"proposals",b"proposals"]) -> None: ...
global___GetProposalsResponse = GetProposalsResponse

class DiscardProposalRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MATCHING_ID_FIELD_NUMBER: builtins.int
    PAIR_FIELD_NUMBER: builtins.int

    @property
    def matching_id(self) -> global___MatchingId: ...

    @property
    def pair(self) -> global___PairIds: ...

    def __init__(self,
        *,
        matching_id : typing.Optional[global___MatchingId] = ...,
        pair : typing.Optional[global___PairIds] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id",u"pair",b"pair"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id",u"pair",b"pair"]) -> None: ...
global___DiscardProposalRequest = DiscardProposalRequest

class DiscardProposalResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STATUS_FIELD_NUMBER: builtins.int

    @property
    def status(self) -> global___StatusMessage: ...

    def __init__(self,
        *,
        status : typing.Optional[global___StatusMessage] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"status",b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"status",b"status"]) -> None: ...
global___DiscardProposalResponse = DiscardProposalResponse

class ExtractRulesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MATCHING_ID_FIELD_NUMBER: builtins.int
    MIN_MATCH_CONFIDENCE_FIELD_NUMBER: builtins.int
    MIN_DISTINCT_CONFIDENCE_FIELD_NUMBER: builtins.int
    min_match_confidence: builtins.float = ...
    min_distinct_confidence: builtins.float = ...

    @property
    def matching_id(self) -> global___MatchingId: ...

    def __init__(self,
        *,
        matching_id : typing.Optional[global___MatchingId] = ...,
        min_match_confidence : builtins.float = ...,
        min_distinct_confidence : builtins.float = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id",u"min_distinct_confidence",b"min_distinct_confidence",u"min_match_confidence",b"min_match_confidence"]) -> None: ...
global___ExtractRulesRequest = ExtractRulesRequest

class ExtractRulesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STATUS_FIELD_NUMBER: builtins.int

    @property
    def status(self) -> global___StatusMessage: ...

    def __init__(self,
        *,
        status : typing.Optional[global___StatusMessage] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"status",b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"status",b"status"]) -> None: ...
global___ExtractRulesResponse = ExtractRulesResponse

class GetRuleSuggestionsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MATCHING_ID_FIELD_NUMBER: builtins.int

    @property
    def matching_id(self) -> global___MatchingId: ...

    def __init__(self,
        *,
        matching_id : typing.Optional[global___MatchingId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id"]) -> None: ...
global___GetRuleSuggestionsRequest = GetRuleSuggestionsRequest

class RuleParam(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    value: typing.Text = ...

    def __init__(self,
        *,
        name : typing.Text = ...,
        value : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"name",b"name",u"value",b"value"]) -> None: ...
global___RuleParam = RuleParam

class Rule(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    FUNCTION_FIELD_NUMBER: builtins.int
    COLUMNS_FIELD_NUMBER: builtins.int
    PARAMS_FIELD_NUMBER: builtins.int
    SUB_RULES_FIELD_NUMBER: builtins.int
    function: typing.Text = ...

    @property
    def columns(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MdcColumn]: ...

    @property
    def params(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RuleParam]: ...

    @property
    def sub_rules(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Rule]: ...

    def __init__(self,
        *,
        function : typing.Text = ...,
        columns : typing.Optional[typing.Iterable[global___MdcColumn]] = ...,
        params : typing.Optional[typing.Iterable[global___RuleParam]] = ...,
        sub_rules : typing.Optional[typing.Iterable[global___Rule]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"columns",b"columns",u"function",b"function",u"params",b"params",u"sub_rules",b"sub_rules"]) -> None: ...
global___Rule = Rule

class RuleStatistics(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    COVERED_POSITIVE_CASES_FIELD_NUMBER: builtins.int
    covered_positive_cases: builtins.float = ...

    def __init__(self,
        *,
        covered_positive_cases : builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"covered_positive_cases",b"covered_positive_cases"]) -> None: ...
global___RuleStatistics = RuleStatistics

class RuleSuggestion(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RULE_FIELD_NUMBER: builtins.int
    STATISTICS_FIELD_NUMBER: builtins.int

    @property
    def rule(self) -> global___Rule: ...

    @property
    def statistics(self) -> global___RuleStatistics: ...

    def __init__(self,
        *,
        rule : typing.Optional[global___Rule] = ...,
        statistics : typing.Optional[global___RuleStatistics] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"rule",b"rule",u"statistics",b"statistics"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"rule",b"rule",u"statistics",b"statistics"]) -> None: ...
global___RuleSuggestion = RuleSuggestion

class BlockingRule(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RULE_FIELD_NUMBER: builtins.int

    @property
    def rule(self) -> global___Rule: ...

    def __init__(self,
        *,
        rule : typing.Optional[global___Rule] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"rule",b"rule"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"rule",b"rule"]) -> None: ...
global___BlockingRule = BlockingRule

class GetRuleSuggestionsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RULE_SUGGESTIONS_FIELD_NUMBER: builtins.int

    @property
    def rule_suggestions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RuleSuggestion]: ...

    def __init__(self,
        *,
        rule_suggestions : typing.Optional[typing.Iterable[global___RuleSuggestion]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"rule_suggestions",b"rule_suggestions"]) -> None: ...
global___GetRuleSuggestionsResponse = GetRuleSuggestionsResponse

class GetStatusRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MATCHING_ID_FIELD_NUMBER: builtins.int

    @property
    def matching_id(self) -> global___MatchingId: ...

    def __init__(self,
        *,
        matching_id : typing.Optional[global___MatchingId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id"]) -> None: ...
global___GetStatusRequest = GetStatusRequest

class GetStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STATUS_FIELD_NUMBER: builtins.int

    @property
    def status(self) -> global___StatusMessage: ...

    def __init__(self,
        *,
        status : typing.Optional[global___StatusMessage] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"status",b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"status",b"status"]) -> None: ...
global___GetStatusResponse = GetStatusResponse

class GetBlockingRulesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MATCHING_ID_FIELD_NUMBER: builtins.int

    @property
    def matching_id(self) -> global___MatchingId: ...

    def __init__(self,
        *,
        matching_id : typing.Optional[global___MatchingId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"matching_id",b"matching_id"]) -> None: ...
global___GetBlockingRulesRequest = GetBlockingRulesRequest

class GetBlockingRulesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    BLOCKING_RULES_FIELD_NUMBER: builtins.int

    @property
    def blocking_rules(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BlockingRule]: ...

    def __init__(self,
        *,
        blocking_rules : typing.Optional[typing.Iterable[global___BlockingRule]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"blocking_rules",b"blocking_rules"]) -> None: ...
global___GetBlockingRulesResponse = GetBlockingRulesResponse

class GetStatusesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...

    def __init__(self,
        ) -> None: ...
global___GetStatusesRequest = GetStatusesRequest

class GetStatusesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MATCHING_STATES_FIELD_NUMBER: builtins.int

    @property
    def matching_states(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StatusMessage]: ...

    def __init__(self,
        *,
        matching_states : typing.Optional[typing.Iterable[global___StatusMessage]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"matching_states",b"matching_states"]) -> None: ...
global___GetStatusesResponse = GetStatusesResponse

class AiMatchingDataRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MASTER_LAYER_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    COLUMNS_FIELD_NUMBER: builtins.int
    SORT_COLUMN_FIELD_NUMBER: builtins.int
    master_layer: typing.Text = ...
    name: typing.Text = ...
    sort_column: typing.Text = ...

    @property
    def columns(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MdcColumn]: ...

    def __init__(self,
        *,
        master_layer : typing.Text = ...,
        name : typing.Text = ...,
        columns : typing.Optional[typing.Iterable[global___MdcColumn]] = ...,
        sort_column : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"columns",b"columns",u"master_layer",b"master_layer",u"name",b"name",u"sort_column",b"sort_column"]) -> None: ...
global___AiMatchingDataRequest = AiMatchingDataRequest

class MdcRow(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DATA_FIELD_NUMBER: builtins.int
    data: builtins.bytes = ...

    def __init__(self,
        *,
        data : builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"data",b"data"]) -> None: ...
global___MdcRow = MdcRow

class ProvideDataResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DATA_FIELD_NUMBER: builtins.int

    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MdcRow]: ...

    def __init__(self,
        *,
        data : typing.Optional[typing.Iterable[global___MdcRow]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"data",b"data"]) -> None: ...
global___ProvideDataResponse = ProvideDataResponse
