# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: term_suggestions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='term_suggestions.proto',
  package='ataccama.aicore.term_suggestions',
  syntax='proto3',
  serialized_options=b'\n-com.ataccama.one.aicore.termsuggestions.protoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16term_suggestions.proto\x12 ataccama.aicore.term_suggestions\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x01\n\x17GetTopKNeighborsRequest\x12?\n\nattributes\x18\x01 \x03(\x0b\x32+.ataccama.aicore.term_suggestions.Attribute\x12;\n\x17\x64\x65sired_cache_freshness\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x95\x01\n\x18GetTopKNeighborsResponse\x12\x44\n\x0fneighbors_batch\x18\x01 \x03(\x0b\x32+.ataccama.aicore.term_suggestions.Neighbors\x12\x33\n\x0f\x63\x61\x63he_freshness\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x17\n\tAttribute\x12\n\n\x02id\x18\x01 \x01(\t\"J\n\tNeighbors\x12=\n\tneighbors\x18\x01 \x03(\x0b\x32*.ataccama.aicore.term_suggestions.Neighbor\"(\n\x08Neighbor\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\"9\n\x13SetThresholdRequest\x12\x0f\n\x07term_id\x18\x01 \x01(\t\x12\x11\n\tthreshold\x18\x02 \x01(\x02\"I\n\x14SetThresholdResponse\x12\x1a\n\x12previous_threshold\x18\x01 \x01(\x02\x12\x15\n\rnew_threshold\x18\x02 \x01(\x02\"?\n\x1aSetAdaptiveLearningRequest\x12\x0f\n\x07term_id\x18\x01 \x01(\t\x12\x10\n\x08\x61\x64\x61ptive\x18\x02 \x01(\x08\"N\n\x1bSetAdaptiveLearningResponse\x12\x19\n\x11previous_adaptive\x18\x01 \x01(\x08\x12\x14\n\x0cnew_adaptive\x18\x02 \x01(\x08\x32\xb7\x03\n\x0fTermSuggestions\x12\x8b\x01\n\x10GetTopKNeighbors\x12\x39.ataccama.aicore.term_suggestions.GetTopKNeighborsRequest\x1a:.ataccama.aicore.term_suggestions.GetTopKNeighborsResponse\"\x00\x12\x7f\n\x0cSetThreshold\x12\x35.ataccama.aicore.term_suggestions.SetThresholdRequest\x1a\x36.ataccama.aicore.term_suggestions.SetThresholdResponse\"\x00\x12\x94\x01\n\x13SetAdaptiveLearning\x12<.ataccama.aicore.term_suggestions.SetAdaptiveLearningRequest\x1a=.ataccama.aicore.term_suggestions.SetAdaptiveLearningResponse\"\x00\x42\x31\n-com.ataccama.one.aicore.termsuggestions.protoP\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_GETTOPKNEIGHBORSREQUEST = _descriptor.Descriptor(
  name='GetTopKNeighborsRequest',
  full_name='ataccama.aicore.term_suggestions.GetTopKNeighborsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='attributes', full_name='ataccama.aicore.term_suggestions.GetTopKNeighborsRequest.attributes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='desired_cache_freshness', full_name='ataccama.aicore.term_suggestions.GetTopKNeighborsRequest.desired_cache_freshness', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=245,
)


_GETTOPKNEIGHBORSRESPONSE = _descriptor.Descriptor(
  name='GetTopKNeighborsResponse',
  full_name='ataccama.aicore.term_suggestions.GetTopKNeighborsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='neighbors_batch', full_name='ataccama.aicore.term_suggestions.GetTopKNeighborsResponse.neighbors_batch', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cache_freshness', full_name='ataccama.aicore.term_suggestions.GetTopKNeighborsResponse.cache_freshness', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=397,
)


_ATTRIBUTE = _descriptor.Descriptor(
  name='Attribute',
  full_name='ataccama.aicore.term_suggestions.Attribute',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ataccama.aicore.term_suggestions.Attribute.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=399,
  serialized_end=422,
)


_NEIGHBORS = _descriptor.Descriptor(
  name='Neighbors',
  full_name='ataccama.aicore.term_suggestions.Neighbors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='neighbors', full_name='ataccama.aicore.term_suggestions.Neighbors.neighbors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=498,
)


_NEIGHBOR = _descriptor.Descriptor(
  name='Neighbor',
  full_name='ataccama.aicore.term_suggestions.Neighbor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ataccama.aicore.term_suggestions.Neighbor.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distance', full_name='ataccama.aicore.term_suggestions.Neighbor.distance', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=500,
  serialized_end=540,
)


_SETTHRESHOLDREQUEST = _descriptor.Descriptor(
  name='SetThresholdRequest',
  full_name='ataccama.aicore.term_suggestions.SetThresholdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='term_id', full_name='ataccama.aicore.term_suggestions.SetThresholdRequest.term_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='threshold', full_name='ataccama.aicore.term_suggestions.SetThresholdRequest.threshold', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=542,
  serialized_end=599,
)


_SETTHRESHOLDRESPONSE = _descriptor.Descriptor(
  name='SetThresholdResponse',
  full_name='ataccama.aicore.term_suggestions.SetThresholdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='previous_threshold', full_name='ataccama.aicore.term_suggestions.SetThresholdResponse.previous_threshold', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new_threshold', full_name='ataccama.aicore.term_suggestions.SetThresholdResponse.new_threshold', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=601,
  serialized_end=674,
)


_SETADAPTIVELEARNINGREQUEST = _descriptor.Descriptor(
  name='SetAdaptiveLearningRequest',
  full_name='ataccama.aicore.term_suggestions.SetAdaptiveLearningRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='term_id', full_name='ataccama.aicore.term_suggestions.SetAdaptiveLearningRequest.term_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='adaptive', full_name='ataccama.aicore.term_suggestions.SetAdaptiveLearningRequest.adaptive', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=676,
  serialized_end=739,
)


_SETADAPTIVELEARNINGRESPONSE = _descriptor.Descriptor(
  name='SetAdaptiveLearningResponse',
  full_name='ataccama.aicore.term_suggestions.SetAdaptiveLearningResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='previous_adaptive', full_name='ataccama.aicore.term_suggestions.SetAdaptiveLearningResponse.previous_adaptive', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new_adaptive', full_name='ataccama.aicore.term_suggestions.SetAdaptiveLearningResponse.new_adaptive', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=741,
  serialized_end=819,
)

_GETTOPKNEIGHBORSREQUEST.fields_by_name['attributes'].message_type = _ATTRIBUTE
_GETTOPKNEIGHBORSREQUEST.fields_by_name['desired_cache_freshness'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETTOPKNEIGHBORSRESPONSE.fields_by_name['neighbors_batch'].message_type = _NEIGHBORS
_GETTOPKNEIGHBORSRESPONSE.fields_by_name['cache_freshness'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_NEIGHBORS.fields_by_name['neighbors'].message_type = _NEIGHBOR
DESCRIPTOR.message_types_by_name['GetTopKNeighborsRequest'] = _GETTOPKNEIGHBORSREQUEST
DESCRIPTOR.message_types_by_name['GetTopKNeighborsResponse'] = _GETTOPKNEIGHBORSRESPONSE
DESCRIPTOR.message_types_by_name['Attribute'] = _ATTRIBUTE
DESCRIPTOR.message_types_by_name['Neighbors'] = _NEIGHBORS
DESCRIPTOR.message_types_by_name['Neighbor'] = _NEIGHBOR
DESCRIPTOR.message_types_by_name['SetThresholdRequest'] = _SETTHRESHOLDREQUEST
DESCRIPTOR.message_types_by_name['SetThresholdResponse'] = _SETTHRESHOLDRESPONSE
DESCRIPTOR.message_types_by_name['SetAdaptiveLearningRequest'] = _SETADAPTIVELEARNINGREQUEST
DESCRIPTOR.message_types_by_name['SetAdaptiveLearningResponse'] = _SETADAPTIVELEARNINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetTopKNeighborsRequest = _reflection.GeneratedProtocolMessageType('GetTopKNeighborsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTOPKNEIGHBORSREQUEST,
  '__module__' : 'term_suggestions_pb2'
  # @@protoc_insertion_point(class_scope:ataccama.aicore.term_suggestions.GetTopKNeighborsRequest)
  })
_sym_db.RegisterMessage(GetTopKNeighborsRequest)

GetTopKNeighborsResponse = _reflection.GeneratedProtocolMessageType('GetTopKNeighborsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETTOPKNEIGHBORSRESPONSE,
  '__module__' : 'term_suggestions_pb2'
  # @@protoc_insertion_point(class_scope:ataccama.aicore.term_suggestions.GetTopKNeighborsResponse)
  })
_sym_db.RegisterMessage(GetTopKNeighborsResponse)

Attribute = _reflection.GeneratedProtocolMessageType('Attribute', (_message.Message,), {
  'DESCRIPTOR' : _ATTRIBUTE,
  '__module__' : 'term_suggestions_pb2'
  # @@protoc_insertion_point(class_scope:ataccama.aicore.term_suggestions.Attribute)
  })
_sym_db.RegisterMessage(Attribute)

Neighbors = _reflection.GeneratedProtocolMessageType('Neighbors', (_message.Message,), {
  'DESCRIPTOR' : _NEIGHBORS,
  '__module__' : 'term_suggestions_pb2'
  # @@protoc_insertion_point(class_scope:ataccama.aicore.term_suggestions.Neighbors)
  })
_sym_db.RegisterMessage(Neighbors)

Neighbor = _reflection.GeneratedProtocolMessageType('Neighbor', (_message.Message,), {
  'DESCRIPTOR' : _NEIGHBOR,
  '__module__' : 'term_suggestions_pb2'
  # @@protoc_insertion_point(class_scope:ataccama.aicore.term_suggestions.Neighbor)
  })
_sym_db.RegisterMessage(Neighbor)

SetThresholdRequest = _reflection.GeneratedProtocolMessageType('SetThresholdRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETTHRESHOLDREQUEST,
  '__module__' : 'term_suggestions_pb2'
  # @@protoc_insertion_point(class_scope:ataccama.aicore.term_suggestions.SetThresholdRequest)
  })
_sym_db.RegisterMessage(SetThresholdRequest)

SetThresholdResponse = _reflection.GeneratedProtocolMessageType('SetThresholdResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETTHRESHOLDRESPONSE,
  '__module__' : 'term_suggestions_pb2'
  # @@protoc_insertion_point(class_scope:ataccama.aicore.term_suggestions.SetThresholdResponse)
  })
_sym_db.RegisterMessage(SetThresholdResponse)

SetAdaptiveLearningRequest = _reflection.GeneratedProtocolMessageType('SetAdaptiveLearningRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETADAPTIVELEARNINGREQUEST,
  '__module__' : 'term_suggestions_pb2'
  # @@protoc_insertion_point(class_scope:ataccama.aicore.term_suggestions.SetAdaptiveLearningRequest)
  })
_sym_db.RegisterMessage(SetAdaptiveLearningRequest)

SetAdaptiveLearningResponse = _reflection.GeneratedProtocolMessageType('SetAdaptiveLearningResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETADAPTIVELEARNINGRESPONSE,
  '__module__' : 'term_suggestions_pb2'
  # @@protoc_insertion_point(class_scope:ataccama.aicore.term_suggestions.SetAdaptiveLearningResponse)
  })
_sym_db.RegisterMessage(SetAdaptiveLearningResponse)


DESCRIPTOR._options = None

_TERMSUGGESTIONS = _descriptor.ServiceDescriptor(
  name='TermSuggestions',
  full_name='ataccama.aicore.term_suggestions.TermSuggestions',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=822,
  serialized_end=1261,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTopKNeighbors',
    full_name='ataccama.aicore.term_suggestions.TermSuggestions.GetTopKNeighbors',
    index=0,
    containing_service=None,
    input_type=_GETTOPKNEIGHBORSREQUEST,
    output_type=_GETTOPKNEIGHBORSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetThreshold',
    full_name='ataccama.aicore.term_suggestions.TermSuggestions.SetThreshold',
    index=1,
    containing_service=None,
    input_type=_SETTHRESHOLDREQUEST,
    output_type=_SETTHRESHOLDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetAdaptiveLearning',
    full_name='ataccama.aicore.term_suggestions.TermSuggestions.SetAdaptiveLearning',
    index=2,
    containing_service=None,
    input_type=_SETADAPTIVELEARNINGREQUEST,
    output_type=_SETADAPTIVELEARNINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TERMSUGGESTIONS)

DESCRIPTOR.services_by_name['TermSuggestions'] = _TERMSUGGESTIONS

# @@protoc_insertion_point(module_scope)
