"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class GetTopKNeighborsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ATTRIBUTES_FIELD_NUMBER: builtins.int
    DESIRED_CACHE_FRESHNESS_FIELD_NUMBER: builtins.int

    @property
    def attributes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Attribute]: ...

    @property
    def desired_cache_freshness(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    def __init__(self,
        *,
        attributes : typing.Optional[typing.Iterable[global___Attribute]] = ...,
        desired_cache_freshness : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"desired_cache_freshness",b"desired_cache_freshness"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"attributes",b"attributes",u"desired_cache_freshness",b"desired_cache_freshness"]) -> None: ...
global___GetTopKNeighborsRequest = GetTopKNeighborsRequest

class GetTopKNeighborsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NEIGHBORS_BATCH_FIELD_NUMBER: builtins.int
    CACHE_FRESHNESS_FIELD_NUMBER: builtins.int

    @property
    def neighbors_batch(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Neighbors]: ...

    @property
    def cache_freshness(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    def __init__(self,
        *,
        neighbors_batch : typing.Optional[typing.Iterable[global___Neighbors]] = ...,
        cache_freshness : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"cache_freshness",b"cache_freshness"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"cache_freshness",b"cache_freshness",u"neighbors_batch",b"neighbors_batch"]) -> None: ...
global___GetTopKNeighborsResponse = GetTopKNeighborsResponse

class Attribute(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    id: typing.Text = ...

    def __init__(self,
        *,
        id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"id",b"id"]) -> None: ...
global___Attribute = Attribute

class Neighbors(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NEIGHBORS_FIELD_NUMBER: builtins.int

    @property
    def neighbors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Neighbor]: ...

    def __init__(self,
        *,
        neighbors : typing.Optional[typing.Iterable[global___Neighbor]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"neighbors",b"neighbors"]) -> None: ...
global___Neighbors = Neighbors

class Neighbor(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    DISTANCE_FIELD_NUMBER: builtins.int
    id: typing.Text = ...
    distance: builtins.float = ...

    def __init__(self,
        *,
        id : typing.Text = ...,
        distance : builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"distance",b"distance",u"id",b"id"]) -> None: ...
global___Neighbor = Neighbor

class SetThresholdRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TERM_ID_FIELD_NUMBER: builtins.int
    THRESHOLD_FIELD_NUMBER: builtins.int
    term_id: typing.Text = ...
    threshold: builtins.float = ...

    def __init__(self,
        *,
        term_id : typing.Text = ...,
        threshold : builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"term_id",b"term_id",u"threshold",b"threshold"]) -> None: ...
global___SetThresholdRequest = SetThresholdRequest

class SetThresholdResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PREVIOUS_THRESHOLD_FIELD_NUMBER: builtins.int
    NEW_THRESHOLD_FIELD_NUMBER: builtins.int
    previous_threshold: builtins.float = ...
    new_threshold: builtins.float = ...

    def __init__(self,
        *,
        previous_threshold : builtins.float = ...,
        new_threshold : builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"new_threshold",b"new_threshold",u"previous_threshold",b"previous_threshold"]) -> None: ...
global___SetThresholdResponse = SetThresholdResponse

class SetAdaptiveLearningRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TERM_ID_FIELD_NUMBER: builtins.int
    ADAPTIVE_FIELD_NUMBER: builtins.int
    term_id: typing.Text = ...
    adaptive: builtins.bool = ...

    def __init__(self,
        *,
        term_id : typing.Text = ...,
        adaptive : builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"adaptive",b"adaptive",u"term_id",b"term_id"]) -> None: ...
global___SetAdaptiveLearningRequest = SetAdaptiveLearningRequest

class SetAdaptiveLearningResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PREVIOUS_ADAPTIVE_FIELD_NUMBER: builtins.int
    NEW_ADAPTIVE_FIELD_NUMBER: builtins.int
    previous_adaptive: builtins.bool = ...
    new_adaptive: builtins.bool = ...

    def __init__(self,
        *,
        previous_adaptive : builtins.bool = ...,
        new_adaptive : builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"new_adaptive",b"new_adaptive",u"previous_adaptive",b"previous_adaptive"]) -> None: ...
global___SetAdaptiveLearningResponse = SetAdaptiveLearningResponse
